version: '3.8'

services:
  web:
    build: .
    command: sh /app/start.sh
    volumes:
      - ./localca_project:/app
      - static_volume:/app/staticfiles

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./localca_project:/app
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web

volumes:
  static_volume:

