services:
  web:
    build: .
    command: sh start.sh
    volumes:
      - ./localca_project:/app
      - static_volume:/app/staticfiles
      - db:/app/db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./localca_project:/app
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web

volumes:
  static_volume:
  db: 

  #sqlite db will be in /var/lib/docker/volumes/localca_db/_data 

