version: '3.8'

services:
  web:
    build: .
    command: sh -c "gunicorn localca_project.wsgi --bind 0.0.0.0:8000 --worker-class=gthread --threads=4"
    ports:
      - "8000:8000"
    volumes:
      - ./localca_project:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./localca_project:/app
    depends_on:
      - web

